mongodb:
  children:
    master:
      hosts:
        mongo-vm01:
          ansible_host: 192.168.0.1
        
    replica:
      hosts:
        mongo-vm02:
          ansible_host: 192.168.0.2
        
    arbiter:
      hosts:
        mongo-vm03:
          ansible_host: 192.168.0.3
        