---
# tasks file for installing pymongo

- name: Install PyMongo package
  ansible.builtin.apt:
    name: "{{ mongodb_pymongo_package }}"
  when: not mongodb_pymongo_from_pip

- name: Install PIP
  ansible.builtin.apt:
    pkg: "{{ mongodb_pymongo_deps }}"
  when: mongodb_pymongo_from_pip | bool

  # TODO: check if it is still needed for Debian/Ubuntu
- name: Install setuptools (required for ansible 2.7+)
  ansible.builtin.apt:
    pkg: "{{ mongodb_python_setuptools }}"
  when: mongodb_pymongo_from_pip | bool

- name: Install PyMongo from PIP
  ansible.builtin.pip:
    name: pymongo
    state: "{{ mongodb_pymongo_pip_version is defined | ternary('present', 'latest') }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
    executable: "{{ mongodb_pip_executable }}"
  when: mongodb_pymongo_from_pip | bool
