---
mongodb_root_user_name: "{{ lookup('env','mongodb_root_user_name') }}"
mongodb_root_user_password: "{{ lookup('env','mongodb_root_user_password') }}"
mongodb_backup_user_name: "{{ lookup('env','mongodb_backup_user_name') }}"
mongodb_backup_user_password: "{{ lookup('env','mongodb_backup_user_password') }}"

