---
mongodb_package: "percona-server-mongodb"
mongodb_net_bindip: "0.0.0.0"
mongodb_version: "4.4"
mongodb_replication_replset: "rs0"
mongodb_login_host: "{{ hostvars[groups['master'][0]].ansible_default_ipv4.address }}"
mongodb_net_maxconns: 51200
mongodb_config:
  replication:
    - "enableMajorityReadConcern: true"

mongodb_storage_dbpath: "/mongodb/data"
mongodb_systemlog_path: "/mongodb/logs/mongod.log"

mongodb_root_user_name: "{{ lookup('env','mongodb_root_user_name') }}"
mongodb_root_user_password: "{{ lookup('env','mongodb_root_user_password') }}"
mongodb_backup_user_name: "{{ lookup('env','mongodb_backup_user_name') }}"
mongodb_backup_user_password: "{{ lookup('env','mongodb_backup_user_password') }}"

mongodb_operation_profiling_slow_op_threshold_ms: 10000
mongodb_operation_profiling_mode: "slowOp"

mongodb_systemlog_component:
  accessControl:
    verbosity: 5
  command:
    verbosity: 5
  write:
    verbosity: 5
  
mongodb_logrotate: true
mongodb_backup: true
mongodb_backup_path: "/mongodb/backups"
mongodb_backup_path_hot_storage: "/mongodb/HotBackups"
mongodb_backup_store_days: 3
mongodb_backup_cron_time:
  hour: 1
  minute: 0

mongodb_disable_transparent_hugepages: true
vm_swappiness: "1"
vm_dirty_ratio: "15"
vm_dirty_background_ratio: "5"