---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 library --ignore=E501,E402
platforms:
  - name: mongo1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    groups:
      - mongo_master
provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare:  ${MOLECULE_PLAYBOOK:-prepare.yml}
  env:
    MONGODB_VERSION: ${MONGODB_VERSION:-4.4}
    MONGODB_PACKAGE: ${MONGODB_PACKAGE:-mongodb-org}
    AUTH_STATE: ${AUTH_STATE:-disabled}
  inventory:
    host_vars:
      mongo1:
        ansible_python_interpreter: auto_silent
        mongodb_net_bindip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }},127.0.0.1"
        mongodb_master: true
        mongodb_replication_params:
          - host_name: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }}"
verifier:
  name: ansible
