---
- name: Include pbm_create_user.yml
  include: pbm_create_user.yml
  when: mongodb_backup_state == "present"
  tags: [ pbm-create-user]

- name: Include pbm_configure.yml
  include: pbm_configure.yml
  when: mongodb_backup_state == "present"
  tags: [ pbm-configure ]

- name: Include pbm_remove.yml
  include: pbm_remove.yml
  when: mongodb_backup_state == "absent"
  tags: [ pbm-remove ]
