--- 
- name: Create file pbm-agent
  template:
    src: pbm-agent.j2
    dest: /etc/sysconfig/pbm-agent
  when: not ansible_check_mode

- name: Create file pbm_config.yml
  template:
    src: pbm_config.yml.j2
    dest: /mongodb/pbm_config.yml
    owner: pbm
    group: pbm
    mode: 0664
  when: not ansible_check_mode

- name: Alter owner backup directory
  file:
    path: "{{ mongodb_backup_path }}"
    owner: pbm
    group: pbm
  when: not ansible_check_mode

- name: PBM Config PBM_MONGODB_URI
  command: pbm config --file /mongodb/pbm_config.yml --mongodb-uri "mongodb://{{ mongodb_pbm_user_name }}:{{ mongodb_pbm_user_name_password }}@{{ inventory_hostname }}:{{ mongodb_net_port|default('27017') }}/admin"
  when: mongodb_replication_replset | length == 0

- name: PBM Config PBM_MONGODB_URI to Replicaset
  command: pbm config --file /mongodb/pbm_config.yml --mongodb-uri "mongodb://{{ mongodb_pbm_user_name }}:{{ mongodb_pbm_user_name_password }}@{{ inventory_hostname }}:{{ mongodb_net_port|default('27017') }}/admin?replicaSet={{ mongodb_replication_replset }}"
  when: mongodb_replication_replset | length > 0

- name: PBM Enable Point-in-Time Recovery
  command: pbm config --set pitr.enabled=true --mongodb-uri "mongodb://{{ mongodb_pbm_user_name }}:{{ mongodb_pbm_user_name_password }}@{{ inventory_hostname }}:{{ mongodb_net_port|default('27017') }}/admin?replicaSet={{ mongodb_replication_replset }}"
  when: 
    - mongodb_replication_replset | length > 0
    - mongodb_backup_pbm_pitr_enable|bool

- name: Start service pbm-agent
  service:
    name: "pbm-agent"
    state: started

- name: Add PBM_MONGODB_URI to bash profile
  lineinfile:
    path: /root/.bash_profile
    line: 'export PBM_MONGODB_URI="mongodb://{{ mongodb_pbm_user_name }}:{{ mongodb_pbm_user_name_password }}@{{ inventory_hostname }}:{{ mongodb_net_port|default("27017") }}/admin"'
  when: mongodb_replication_replset | length == 0

- name: Add PBM_MONGODB_URI to bash profile to Replicaset
  lineinfile:
    path: /root/.bash_profile
    line: 'export PBM_MONGODB_URI="mongodb://{{ mongodb_pbm_user_name }}:{{ mongodb_pbm_user_name_password }}@{{ inventory_hostname }}:{{ mongodb_net_port|default("27017") }}/admin?replicaSet={{ mongodb_replication_replset }}"'
  when: mongodb_replication_replset | length > 0