---

- name: Establish some role-related facts
  set_fact:
    mongodb_major_version: "{{ mongodb_version[0:3] }}"

#- name: Add repository
#  yum_repository:
#    name: epel
#    description: EPEL YUM repo
#    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#  become: yes
      
#- name: Install EPEL release repository
#  package:
#    name: epel-release
#    state: present
#  become: yes

- name: Add YUM repository
  template:
    src: mongodb.repo.j2
    dest: /etc/yum.repos.d/mongodb.repo
    mode: 0644
  with_items: "{{ mongodb_major_version }}"
  loop_control:
    loop_var: version_item
  when: mongodb_package == 'mongodb-org'
  become: yes

- name: Install MongoDB package
  yum:
    name: "{{ mongodb_package }}{% if (mongodb_version | length > 3) %}={{ mongodb_version }}{% endif %}"
    state: "{{ mongodb_package_state }}"
    lock_timeout: "{{ yum_lock_timeout }}"

- name: Install numactl package
  yum:
    name: numactl
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_use_numa | bool

- name: Install PyMongo package
  yum:
    name: python3-pymongo
    state: present
    lock_timeout: "{{ yum_lock_timeout }}"
  when: not mongodb_pymongo_from_pip

- name: Install pip
  yum:
    name:
      - python3-devel
      - python3-pip
    lock_timeout: "{{ yum_lock_timeout }}"
  when: mongodb_pymongo_from_pip | bool

- name: Install PyMongo with pip
  pip:
    name: pymongo
    state: "{{ mongodb_pymongo_pip_version is defined | ternary('present', 'latest') }}"
    version: "{{ mongodb_pymongo_pip_version | default(omit) }}"
  when: mongodb_pymongo_from_pip | bool
