name: Amazon Linux 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  python3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        molecule_distro:
          - amazonlinux2
        mongodb_version:
          - '5.0'
          - '4.4'
          - '4.2'
          - '4.0'
          - '3.6'
    env:
      MONGODB_VERSION: ${{ matrix.mongodb_version }}
      MOLECULE_DISTRO: ${{ matrix.molecule_distro }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare tests
        run: pip install -r requirements.txt
      - name: Run default test
        run: export "PATH=/home/runner/.local/bin:$PATH" && molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: Run default test with enabled authentication
        run: export "PATH=/home/runner/.local/bin:$PATH" && AUTH_STATE=enabled molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: Run cluster test
        run: export "PATH=/home/runner/.local/bin:$PATH" && molecule test -s cluster
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
      - name: Run cluster test with enabled authentication
        run: export "PATH=/home/runner/.local/bin:$PATH" && AUTH_STATE=enabled molecule test -s cluster
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
